### PR TITLE
Moved app files to src/

### PR DESCRIPTION
**Pull request by Fraasi**
More house cleaning:smile: I wanted to make another branch for this but apparently github doesn't allow to 'pull request a new branch', there should be already a branch to make the pull request to.  
Anyway, if you are unsure about this, you can always make a 'backup' branch yourself before merging this pull request to master. Of course I tested this and it didn' brake anything (so far:relaxed:).  

Next up: little changes to your about page.  
By the way, what's your plan on implementing the backend system? Personally I don't think that's necessary for this kind of an app. But maybe a 'export all clipboard notes as a text file'-button wold be good to have, if people want to have a backup of all the things.

### CODE REVIEW

**Comment by Fraasi** [comment]
So I made another pull request and apparently it got 'merged' with this unmerged pull request.  
Oh well, two things in one.  

-----------------------
Ok, I added some functionality to the about page. Now you can click on the version & link to get easy access to the apps repo.

I made an about.js file to keep javascript separate from the about.html.   
And since you had 'Add comments to everything!', in the todo, I put comments pretty much everywhere:sunglasses:

I also removed the empty renderer.js & updated todo.

**Comment by axesve** [comment]
Okay, this is epic, it's very nice that you are so dedicated to this little project really brings a tear to my eye knowing someone finds a use for the software and also wanting to contribute thank you for making my week a whole lot better 😄

One goal I had with this software was to make it into a cloud based system where it would sync any device, including phone to one storage of clipboards. I had gotten a pretty decent way with this and I am actually planning on setting it up in the future once I get more spare time, but adding a "save to txt" is actually not a bad idea, I do fear tho that the layout will be kinda weird, one way to get it readable is (TEXT + TAG / DATE) or something like it.

Really like the idea of removing most of the Jquery and going vanilla JS, hopefully I'll be able to actually do something too next week...

Also, I am adding you to the contributors list 😄

**Comment by Fraasi** [comment]
Well thank you:bowtie: (I just found out about this https://www.webpagefx.com/tools/emoji-cheat-sheet/)  
Actually I've been looking for a repo to contribute for some time, because I would like to learn more about git & github & working with others and not just by myself in my own projects. Plus I know how it is when you're struggling and learning to finally get a little help.   
But most of the projects I find interesting are way out my coding skills. So I stumbled upon your repo and you had a great idea for an app and a really nice start. Even thought your code is all over the place I thought this is something I can help make better. So consider this an early xmas present if you like:gift:

Export doesn't have to be .txt, could be also .json or whatever/however you have it setup now. But in this kind of apps it's really nice to 'get the data out' of the app so you can fiddle with it with any texteditor if you so choose.

About the cloud. Yes it would be nice feature, but also lot of work. You have to setup a database, put somekind of id system/password thing in place and do all kind of authentication everywhere. Maybe that's something you can add to the app at some later time, but of course: it's your app and if you already have some of the code ready, let it fly:balloon:

By the way, I don't know if you have taken a look at my repos, but here's a quick link to electron project I did awhile back https://github.com/Fraasi/PDTapp

**Comment by axesve** [comment]
This project was in its early stages, I had not gotten to the clean up myself to be honest, also this was my first time using Electron so I can agree my stuff were all over the directories and it kinda made my feel uneasy...

I was thinking since most people cant really read .JSON files a formatted .txt file would be better for end users, get your point tho!

I've made some cloud systems before using pure php and mysql, it's easier than you think but time and money consuming.

Cool little app you've got there, the design is kinda boring I would've changed fonts, colors and try to setup a structored way to display data, removed the borders and made background colors instead, removed the top "Home" and putting the date at the bottom since it should not be the key focus.

**Comment by Fraasi** [comment]
Thanks for the feedback. I'm not a designer person at all, so I usually just throw something together to get quickly back to coding javascript and then never get around updating my styles. Yes the front page is a little cluttered, have to take the weather things out of it now that I have this project under construction https://github.com/Fraasi/Saeae

**Pull request merged**
